name: 'Data Migration Util Stager'
description: 'Prep files for sfdx data migration utility'
inputs:
  parentDir:  # Parent Directory
    description: 'Parent diretory containing data loads'
    required: true
    default: 'data'
outputs:
  dirs: # array of directories
    description: 'Array of directories'
  hasData: # boolean has data
    description: 'Directory has data loads'
  directoryCount: # count of data load directories
    description: 'Count of data load directories under parent.'
runs:
  using: 'node12'
  main: 'index.js'
